name: homecare_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  cupertino_icons: ^1.0.8
  lottie: ^2.7.0
  smooth_page_indicator: ^1.1.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2 
  fluttertoast: ^8.0.9 
  dropdown_search: ^2.0.0 
  google_fonts: ^6.1.0
  intl: ^0.18.0 
  flutter_smart_dialog: ^4.9.5

  #awesome_dialog: ^3.2.1
  #rive: ^0.13.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  #rive: ^0.13.20         
  #rive_common: ^0.4.15

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.jpg
